spring.application.name=ecom-application
spring.datasource.url=jdbc:mysql://database-1.c528y4cqqb5x.ap-south-1.rds.amazonaws.com/ecommerce_db
spring.datasource.username=admin
spring.datasource.password=4e9ihnK7M8nySfu

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
