spring.application.name=ecom-application

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#server.shutdown=graceful
#
#
#management.info.env.enabled=true
#management.endpoint.shutdown.enabled=true
#
#info.app.name=ECommerceBackendspringboot
#info.app.description=This is a complete E-commerce backend project made with springboot maven
#info.app.version=1.0.0

#for reducing time consumption in the startup of the app
spring.devtools.add-properties=false
spring.main.lazy-initialization=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false